### ISSUE TITLE
WPC loss ?

### ISSUE THREAD

**Issue by AILMLHL** [martinmamql/relative_predictive_coding#2]
There is no WPC loss-related code here. May I ask when it will be open-sourced?

**Comment by martinmamql** [comment]
Hi AILMLHL,

I apologize for the oversight -- unfortunately I am not able to recover WPC implementation right now, but feel free to implement WPC based on one of the losses (NWJ, JS or DV) and apply the gradient_penalty in https://github.com/martinmamql/relative_predictive_coding/blob/main/vision/objective.py#L36 to enforce Lipschitz continuity on the positive and negative scores.
